version: '3.4'

services:
  dockerdemo.webapp:
    image: dockerdemowebapp:dev
    container_name: DockerDemo.WebApp
    build:
      target: base
      labels:
        com.microsoft.created-by: "visual-studio"
        com.microsoft.visual-studio.project-name: "DockerDemo.WebApp"
    environment:
      - DOTNET_USE_POLLING_FILE_WATCHER=1
      #- NUGET_FALLBACK_PACKAGES=$container_paths_to_fallback_packages_dockerdemo.webapp$
    volumes:
      - D:\repos\docker\linux_redis_netcore\linux_redis_netcore\DockerDemo.WebApp:/app
      - D:\repos\docker\linux_redis_netcore\linux_redis_netcore:/src
      - C:\Users\raj.kumar1\vsdbg\vs2017u5:/remote_debugger:rw
#$nuget_volume_mapping_dockerdemo.webapp$
      - ${APPDATA}/ASP.NET/Https:/root/.aspnet/https:ro
      - ${APPDATA}/Microsoft/UserSecrets:/root/.microsoft/usersecrets:ro

    entrypoint: tail -f /dev/null
    labels:
      com.microsoft.visualstudio.debuggee.program: "dotnet"
      #com.microsoft.visualstudio.debuggee.arguments: " $debuggee_arguments_probing_paths_dockerdemo.webapp$ \"bin/Debug/netcoreapp2.2/DockerDemo.WebApp.dll\""
      com.microsoft.visualstudio.debuggee.workingdirectory: "/app"
      com.microsoft.visualstudio.debuggee.killprogram: "/bin/sh -c \"if PID=$$(pidof dotnet); then kill $$PID; fi\""
    tty: true