apiVersion: apps/v1beta1
kind: Deployment
metadata:
  name: mysamplekubapps
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: demo-kub-apps
    spec:
      containers:
        - name: mssample-services-app
          image: dockerhub.io/rajkrs/docker_linux_redis_netcore:latest
          ports:
            - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
    name: demo-kub-apps
spec:
  ports:
    - name: http-port
      port: 80
      targetPort: 80
  selector:
    app: demo-kub-apps
  type: LoadBalancer